# Base image
FROM azul/zulu-openjdk:17

# Set working directory
WORKDIR /app

# Copy the JAR file into the container
COPY build/libs/*.jar pingpong-prod.jar

# Expose the port on which your application listens
EXPOSE 8080

# Set the entrypoint command to run your application
ENTRYPOINT ["java", "-jar", "pingpong-prod.jar"]
