# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CD

#dev브랜치가 push될 때 동작
on:
  push:
    branches: [ "develop" ]
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 소스 체크아웃
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.HYESOO_GITHUB_TOKEN }}
        submodules: 'true'
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # Gradlew 권한 설정
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # 빌드단계에서 테스트는 제외.
    - name: Build with Gradle
      if: contains(github.ref, 'develop')
      run: SPRING_PROFILES_ACTIVE=[dev] ./gradlew clean copyGitSubmodule build -x test

    # 테스트
    - name: Test with Gradle
      run: SPRING_PROFILES_ACTIVE=[test] ./gradlew copyGitSubmodule test
    
    # SCP방식으로 Deploy
    - name: Deploy use SCP
      uses: appleboy/scp-action@master
      id: deploy-dev
      if: contains(github.ref, 'develop')
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_KEY }}
        #password: ${{ secrets.NPC_DEV_SERVER_PASSWORD }}
        port: ${{ secrets.DEV_SERVER_PORT }}
        source: "./build/libs/*.jar"
        target: "~/deploy"

    # 스크립트 실행
    - name: Execute Server Init Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_KEY }}
        #password: ${{ secrets.NPC_DEV_SERVER_PASSWORD }}
        port: ${{ secrets.DEV_SERVER_PORT }}
        script_stop: true
        script: chmod +x ~/deploy/deploy.sh && sh ~/deploy/deploy.sh
